name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2

    - name: Generate Project Files
      run: |
        cd ..
        curl --output premake.zip --url https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip 
        unzip premake.zip

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Solution
      run: msbuild -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo CountingBot.sln